export const wordsArr = [
    {title: "Red",
    photo: "https://funart.pro/uploads/posts/2021-04/1618554563_39-funart_pro-p-oboi-fon-svetlo-krasnii-tsvet-40.jpg",
    mean: "color",
    transcript: "|red|",
    translate: "красный",
    theme: "Colors",
    sample: "red dress",
    isSelected: true,
    },
    {title: "Blue",
    photo: "https://miro.medium.com/max/1280/0*xCXUvGbrpndOWTw5.jpg",
    mean: "color",
    transcript: " |bluː| ",
    translate: "синий",
    theme: "Colors",
    sample: "blue hat",
    },
    {title: "Yellow",
    photo: "https://funart.pro/uploads/posts/2021-04/1618493424_5-funart_pro-p-oboi-fon-zheltii-tsvet-6.png",
    mean: "color",
    transcript: "|ˈjeləʊ| ",
    translate: "жёлтый",
    theme: "Colors",
    sample: "yellow shirt",
    },

    {title: "Black",
    photo: "https://bogatyr.club/uploads/posts/2021-11/thumbs/1636953181_5-bogatyr-club-p-glubokii-chernii-fon-5.jpg",
    mean: "color",
    transcript: "|blæk| ",
    translate: "чёрный",
    theme: "Colors",
    sample: "black coat",
    },
    
    
    ]

 