export const cardsArr = [
    {title: "Red",
    photo: "https://media.istockphoto.com/id/186543936/photo/fashion-in-new-york-city.jpg?s=612x612&w=0&k=20&c=iuvNG1M5Kgqp7PilQ8FpwgkUS0pr5ok7EdwXu5bCHG0=",
    mean: "color",
    question: "What color is her dress?",
    transcript: "|red|",
    translate: "красный",
    theme: "Colors",
    sample: "red dress",
    
    },
    {title: "Blue",
    photo: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-514289018-1491253643.jpg?crop=1.00xw:0.742xh;0,0.123xh&resize=1200:*",
    mean: "color",
    question: "What color is her hat?",
    transcript: " |bluː| ",
    translate: "синий",
    theme: "Colors",
    sample: "blue hat",
    },
    {title: "Yellow",
    photo: "https://www.pakstyle.pk/img/products/l/p15018-yellow-plain-round-neck-t-shirt.jpg",
    mean: "color",
    question: "What color is his T-shirt?",
    transcript: "|ˈjeləʊ| ",
    translate: "жёлтый",
    theme: "Colors",
    sample: "yellow shirt",
    },

    {title: "Black",
    photo: "https://i.etsystatic.com/11627371/r/il/9fbca8/3541653894/il_fullxfull.3541653894_q58o.jpg",
    mean: "color",
    question: "What color is her coat?",
    transcript: "|blæk| ",
    translate: "чёрный",
    theme: "Colors",
    sample: "black coat",
    },
    
    ]

 